#!/bin/sh

SERIAL_USB_DEV=/dev/ttyUSB0

if uname -a | grep Darwin > /dev/null
then
  SERIAL_USB_DEV=/dev/cu.usbserial
fi

if [ ! -f ${SERIAL_USB_DEV} ]
then
   "Echo no USB ${SERIAL_USB_DEV}"
   exit -1
fi

screen ${SERIAL_USB_DEV} 115200
