#!/bin/sh

SERIAL_USB_DEV=/dev/ttyUSB0

if uname -a | grep Darwin > /dev/null
then
  SERIAL_USB_DEV=/dev/cu.usbserial
fi


[ ! -f ${SERIAL_USB_DEV} ] && "Echo no USB ${SERIAL_USB_DEV}" && exit -1

screen ${SERIAL_USB_DEV} 115200
